name: copy target.yml from sync_source_repo
on:
  repository_dispatch:
    types: [target-updated]
jobs:
  copy-target:
    name: copy files
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone sync_source_repo
        uses: actions/checkout@v2
        with:
          repository: KosukeKokubun/sync_source_repo
          path: sync_source_repo
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: copy files from sources
        run: cp -r sync_source_repo/test/sources_files test/
      - name: clean sync_source_repo
        run: rm -rf sync_source_repo
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: 'copy target.yml'
          branch: copy_target
          branch-suffix: timestamp
          delete-branch: true
          title: 'updated target.yml'